### ISSUE TITLE
TODO: Change port/ip options to be non-broken

### ISSUE THREAD

**Issue by amsam0** [SuperVK/RLBotJS#16]
On https://github.com/SuperVK/RLBotJS/blob/master/src/BotManager.js#L34 the port will be changed to either true or false... Same with ip

**Comment by SuperVK** [comment]
I think those just need to be deleted, there is no reason to set the port outside of port.cfg, because the python has a mismatch (also yes it was me who implemented it)

**Comment by SuperVK** [comment]
issue outdated, should be fixed aswell
